name: Limpeza Automática de Currículos

on:
  # Executa todos os dias às 09:00 UTC
  schedule:
    - cron: '0 9 * * *'
  
  # Permite execução manual
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Instalar dependências
      run: npm install
    
    - name: Executar limpeza de currículos
      env:
        GITHUB_USER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        BRANCH: ${{ github.ref_name }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CURRICULO_DIR: ${{ vars.CURRICULO_DIR || 'curriculos' }}
      run: node cleanup-curriculos.js
    
    - name: Log do resultado
      run: echo "Limpeza de currículos executada com sucesso em $(date)"

